name: 'analytics'
version: '1.0.0'

profile: 'analytics'

model-paths: ["analytics/models"]
macro-paths: ["analytics/macros"]
#analysis-paths: ["analytics/analyses"]
#test-paths: ["analytics/tests"]
#seed-paths: ["analytics/seeds"]
#snapshot-paths: ["analytics/snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  analytics:
    staging:
      +database: analytics
      +schema: staging
      +materialized: table
      +docs:
        show: true
    intermediate:
      +database: analytics
      +schema: intermediate
      +materialized: table
      +docs:
        show: true
    core:
      +database: analytics
      +schema: core
      +materialized: table
      +docs:
        show: true