[tool.poetry]
name = "zwift-scout"
version = "0.1.0"
description = ""
authors = ["robgriffin247 <robgriffin247@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
